// compile with:
// protoc --go_out=. --go_opt=paths=source_relative flood.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v4.22.2
// source: flood.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FloodInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The last time (unix timestamp + millis) a print was seen
	// from this player
	LastPrintTime int64 `protobuf:"varint,1,opt,name=last_print_time,json=lastPrintTime,proto3" json:"last_print_time,omitempty"`
	// The first time seen
	FirstPrintTime int64 `protobuf:"varint,2,opt,name=first_print_time,json=firstPrintTime,proto3" json:"first_print_time,omitempty"`
	// The total number of prints seen
	PrintTotal int32 `protobuf:"varint,3,opt,name=print_total,json=printTotal,proto3" json:"print_total,omitempty"`
	// The last time we saw a UI change from this player
	LastUserinfoTime int64 `protobuf:"varint,4,opt,name=last_userinfo_time,json=lastUserinfoTime,proto3" json:"last_userinfo_time,omitempty"`
	// This will be set to the time they joined
	FirstUserinfoTime int64 `protobuf:"varint,5,opt,name=first_userinfo_time,json=firstUserinfoTime,proto3" json:"first_userinfo_time,omitempty"`
	// total UI changes
	UserinfoTotal int32 `protobuf:"varint,6,opt,name=userinfo_total,json=userinfoTotal,proto3" json:"userinfo_total,omitempty"`
}

func (x *FloodInfo) Reset() {
	*x = FloodInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_flood_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FloodInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FloodInfo) ProtoMessage() {}

func (x *FloodInfo) ProtoReflect() protoreflect.Message {
	mi := &file_flood_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FloodInfo.ProtoReflect.Descriptor instead.
func (*FloodInfo) Descriptor() ([]byte, []int) {
	return file_flood_proto_rawDescGZIP(), []int{0}
}

func (x *FloodInfo) GetLastPrintTime() int64 {
	if x != nil {
		return x.LastPrintTime
	}
	return 0
}

func (x *FloodInfo) GetFirstPrintTime() int64 {
	if x != nil {
		return x.FirstPrintTime
	}
	return 0
}

func (x *FloodInfo) GetPrintTotal() int32 {
	if x != nil {
		return x.PrintTotal
	}
	return 0
}

func (x *FloodInfo) GetLastUserinfoTime() int64 {
	if x != nil {
		return x.LastUserinfoTime
	}
	return 0
}

func (x *FloodInfo) GetFirstUserinfoTime() int64 {
	if x != nil {
		return x.FirstUserinfoTime
	}
	return 0
}

func (x *FloodInfo) GetUserinfoTotal() int32 {
	if x != nil {
		return x.UserinfoTotal
	}
	return 0
}

var File_flood_proto protoreflect.FileDescriptor

var file_flood_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x66, 0x6c, 0x6f, 0x6f, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x83, 0x02, 0x0a, 0x09, 0x46, 0x6c, 0x6f, 0x6f, 0x64, 0x49, 0x6e,
	0x66, 0x6f, 0x12, 0x26, 0x0a, 0x0f, 0x6c, 0x61, 0x73, 0x74, 0x5f, 0x70, 0x72, 0x69, 0x6e, 0x74,
	0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0d, 0x6c, 0x61, 0x73,
	0x74, 0x50, 0x72, 0x69, 0x6e, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x28, 0x0a, 0x10, 0x66, 0x69,
	0x72, 0x73, 0x74, 0x5f, 0x70, 0x72, 0x69, 0x6e, 0x74, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x0e, 0x66, 0x69, 0x72, 0x73, 0x74, 0x50, 0x72, 0x69, 0x6e, 0x74,
	0x54, 0x69, 0x6d, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x70, 0x72, 0x69, 0x6e, 0x74, 0x5f, 0x74, 0x6f,
	0x74, 0x61, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x70, 0x72, 0x69, 0x6e, 0x74,
	0x54, 0x6f, 0x74, 0x61, 0x6c, 0x12, 0x2c, 0x0a, 0x12, 0x6c, 0x61, 0x73, 0x74, 0x5f, 0x75, 0x73,
	0x65, 0x72, 0x69, 0x6e, 0x66, 0x6f, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x10, 0x6c, 0x61, 0x73, 0x74, 0x55, 0x73, 0x65, 0x72, 0x69, 0x6e, 0x66, 0x6f, 0x54,
	0x69, 0x6d, 0x65, 0x12, 0x2e, 0x0a, 0x13, 0x66, 0x69, 0x72, 0x73, 0x74, 0x5f, 0x75, 0x73, 0x65,
	0x72, 0x69, 0x6e, 0x66, 0x6f, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x11, 0x66, 0x69, 0x72, 0x73, 0x74, 0x55, 0x73, 0x65, 0x72, 0x69, 0x6e, 0x66, 0x6f, 0x54,
	0x69, 0x6d, 0x65, 0x12, 0x25, 0x0a, 0x0e, 0x75, 0x73, 0x65, 0x72, 0x69, 0x6e, 0x66, 0x6f, 0x5f,
	0x74, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0d, 0x75, 0x73, 0x65,
	0x72, 0x69, 0x6e, 0x66, 0x6f, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x42, 0x29, 0x5a, 0x27, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x70, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x66,
	0x6c, 0x69, 0x6e, 0x67, 0x65, 0x72, 0x2f, 0x71, 0x32, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x64, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_flood_proto_rawDescOnce sync.Once
	file_flood_proto_rawDescData = file_flood_proto_rawDesc
)

func file_flood_proto_rawDescGZIP() []byte {
	file_flood_proto_rawDescOnce.Do(func() {
		file_flood_proto_rawDescData = protoimpl.X.CompressGZIP(file_flood_proto_rawDescData)
	})
	return file_flood_proto_rawDescData
}

var file_flood_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_flood_proto_goTypes = []interface{}{
	(*FloodInfo)(nil), // 0: proto.FloodInfo
}
var file_flood_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_flood_proto_init() }
func file_flood_proto_init() {
	if File_flood_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_flood_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FloodInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_flood_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_flood_proto_goTypes,
		DependencyIndexes: file_flood_proto_depIdxs,
		MessageInfos:      file_flood_proto_msgTypes,
	}.Build()
	File_flood_proto = out.File
	file_flood_proto_rawDesc = nil
	file_flood_proto_goTypes = nil
	file_flood_proto_depIdxs = nil
}
