// compile with:
// protoc --go_out=. --go_opt=paths=source_relative maprotator.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v4.22.2
// source: maprotator.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MapRotationDirection int32

const (
	MapRotationDirection_MapRotationDirectionForward MapRotationDirection = 0
	MapRotationDirection_MapRotationDirectionReverse MapRotationDirection = 1
)

// Enum value maps for MapRotationDirection.
var (
	MapRotationDirection_name = map[int32]string{
		0: "MapRotationDirectionForward",
		1: "MapRotationDirectionReverse",
	}
	MapRotationDirection_value = map[string]int32{
		"MapRotationDirectionForward": 0,
		"MapRotationDirectionReverse": 1,
	}
)

func (x MapRotationDirection) Enum() *MapRotationDirection {
	p := new(MapRotationDirection)
	*p = x
	return p
}

func (x MapRotationDirection) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MapRotationDirection) Descriptor() protoreflect.EnumDescriptor {
	return file_maprotator_proto_enumTypes[0].Descriptor()
}

func (MapRotationDirection) Type() protoreflect.EnumType {
	return &file_maprotator_proto_enumTypes[0]
}

func (x MapRotationDirection) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MapRotationDirection.Descriptor instead.
func (MapRotationDirection) EnumDescriptor() ([]byte, []int) {
	return file_maprotator_proto_rawDescGZIP(), []int{0}
}

type Map struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name           string  `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	MinimumPlayers int32   `protobuf:"varint,2,opt,name=minimum_players,json=minimumPlayers,proto3" json:"minimum_players,omitempty"`
	MaximumPlayers int32   `protobuf:"varint,3,opt,name=maximum_players,json=maximumPlayers,proto3" json:"maximum_players,omitempty"`
	Flags          int64   `protobuf:"varint,4,opt,name=flags,proto3" json:"flags,omitempty"`
	PlayTimes      []int64 `protobuf:"varint,5,rep,packed,name=play_times,json=playTimes,proto3" json:"play_times,omitempty"`
}

func (x *Map) Reset() {
	*x = Map{}
	if protoimpl.UnsafeEnabled {
		mi := &file_maprotator_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Map) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Map) ProtoMessage() {}

func (x *Map) ProtoReflect() protoreflect.Message {
	mi := &file_maprotator_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Map.ProtoReflect.Descriptor instead.
func (*Map) Descriptor() ([]byte, []int) {
	return file_maprotator_proto_rawDescGZIP(), []int{0}
}

func (x *Map) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Map) GetMinimumPlayers() int32 {
	if x != nil {
		return x.MinimumPlayers
	}
	return 0
}

func (x *Map) GetMaximumPlayers() int32 {
	if x != nil {
		return x.MaximumPlayers
	}
	return 0
}

func (x *Map) GetFlags() int64 {
	if x != nil {
		return x.Flags
	}
	return 0
}

func (x *Map) GetPlayTimes() []int64 {
	if x != nil {
		return x.PlayTimes
	}
	return nil
}

type MapRotation struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// arbitrary name
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// unique
	Uuid string `protobuf:"bytes,2,opt,name=uuid,proto3" json:"uuid,omitempty"`
	// the list of maps
	Maps []*Map `protobuf:"bytes,3,rep,name=maps,proto3" json:"maps,omitempty"`
	// which map are we on?
	Index int32 `protobuf:"varint,4,opt,name=index,proto3" json:"index,omitempty"`
	// forward or reverse
	Direction MapRotationDirection `protobuf:"varint,5,opt,name=direction,proto3,enum=proto.MapRotationDirection" json:"direction,omitempty"`
	// how many full rotations have we done?
	Iterations int32 `protobuf:"varint,6,opt,name=iterations,proto3" json:"iterations,omitempty"`
	// how many maps are in this rotation?
	Size int32 `protobuf:"varint,7,opt,name=size,proto3" json:"size,omitempty"`
}

func (x *MapRotation) Reset() {
	*x = MapRotation{}
	if protoimpl.UnsafeEnabled {
		mi := &file_maprotator_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MapRotation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MapRotation) ProtoMessage() {}

func (x *MapRotation) ProtoReflect() protoreflect.Message {
	mi := &file_maprotator_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MapRotation.ProtoReflect.Descriptor instead.
func (*MapRotation) Descriptor() ([]byte, []int) {
	return file_maprotator_proto_rawDescGZIP(), []int{1}
}

func (x *MapRotation) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MapRotation) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *MapRotation) GetMaps() []*Map {
	if x != nil {
		return x.Maps
	}
	return nil
}

func (x *MapRotation) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *MapRotation) GetDirection() MapRotationDirection {
	if x != nil {
		return x.Direction
	}
	return MapRotationDirection_MapRotationDirectionForward
}

func (x *MapRotation) GetIterations() int32 {
	if x != nil {
		return x.Iterations
	}
	return 0
}

func (x *MapRotation) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

var File_maprotator_proto protoreflect.FileDescriptor

var file_maprotator_proto_rawDesc = []byte{
	0x0a, 0x10, 0x6d, 0x61, 0x70, 0x72, 0x6f, 0x74, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xa0, 0x01, 0x0a, 0x03, 0x4d, 0x61,
	0x70, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x27, 0x0a, 0x0f, 0x6d, 0x69, 0x6e, 0x69, 0x6d, 0x75, 0x6d,
	0x5f, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0e,
	0x6d, 0x69, 0x6e, 0x69, 0x6d, 0x75, 0x6d, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x73, 0x12, 0x27,
	0x0a, 0x0f, 0x6d, 0x61, 0x78, 0x69, 0x6d, 0x75, 0x6d, 0x5f, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72,
	0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0e, 0x6d, 0x61, 0x78, 0x69, 0x6d, 0x75, 0x6d,
	0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x66, 0x6c, 0x61, 0x67, 0x73,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x66, 0x6c, 0x61, 0x67, 0x73, 0x12, 0x1d, 0x0a,
	0x0a, 0x70, 0x6c, 0x61, 0x79, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28,
	0x03, 0x52, 0x09, 0x70, 0x6c, 0x61, 0x79, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x22, 0xda, 0x01, 0x0a,
	0x0b, 0x4d, 0x61, 0x70, 0x52, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x12, 0x12, 0x0a, 0x04, 0x75, 0x75, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x75, 0x75, 0x69, 0x64, 0x12, 0x1e, 0x0a, 0x04, 0x6d, 0x61, 0x70, 0x73, 0x18, 0x03, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4d, 0x61, 0x70, 0x52, 0x04,
	0x6d, 0x61, 0x70, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x39, 0x0a, 0x09, 0x64, 0x69,
	0x72, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1b, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4d, 0x61, 0x70, 0x52, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x44, 0x69, 0x72, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x09, 0x64, 0x69, 0x72, 0x65,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1e, 0x0a, 0x0a, 0x69, 0x74, 0x65, 0x72, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x69, 0x74, 0x65, 0x72, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x07, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x2a, 0x58, 0x0a, 0x14, 0x4d, 0x61, 0x70,
	0x52, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x44, 0x69, 0x72, 0x65, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x12, 0x1f, 0x0a, 0x1b, 0x4d, 0x61, 0x70, 0x52, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x44, 0x69, 0x72, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x46, 0x6f, 0x72, 0x77, 0x61, 0x72, 0x64,
	0x10, 0x00, 0x12, 0x1f, 0x0a, 0x1b, 0x4d, 0x61, 0x70, 0x52, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x44, 0x69, 0x72, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x76, 0x65, 0x72, 0x73,
	0x65, 0x10, 0x01, 0x42, 0x29, 0x5a, 0x27, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x70, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x66, 0x6c, 0x69, 0x6e, 0x67, 0x65, 0x72, 0x2f,
	0x71, 0x32, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x64, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_maprotator_proto_rawDescOnce sync.Once
	file_maprotator_proto_rawDescData = file_maprotator_proto_rawDesc
)

func file_maprotator_proto_rawDescGZIP() []byte {
	file_maprotator_proto_rawDescOnce.Do(func() {
		file_maprotator_proto_rawDescData = protoimpl.X.CompressGZIP(file_maprotator_proto_rawDescData)
	})
	return file_maprotator_proto_rawDescData
}

var file_maprotator_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_maprotator_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_maprotator_proto_goTypes = []interface{}{
	(MapRotationDirection)(0), // 0: proto.MapRotationDirection
	(*Map)(nil),               // 1: proto.Map
	(*MapRotation)(nil),       // 2: proto.MapRotation
}
var file_maprotator_proto_depIdxs = []int32{
	1, // 0: proto.MapRotation.maps:type_name -> proto.Map
	0, // 1: proto.MapRotation.direction:type_name -> proto.MapRotationDirection
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_maprotator_proto_init() }
func file_maprotator_proto_init() {
	if File_maprotator_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_maprotator_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Map); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_maprotator_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MapRotation); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_maprotator_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_maprotator_proto_goTypes,
		DependencyIndexes: file_maprotator_proto_depIdxs,
		EnumInfos:         file_maprotator_proto_enumTypes,
		MessageInfos:      file_maprotator_proto_msgTypes,
	}.Build()
	File_maprotator_proto = out.File
	file_maprotator_proto_rawDesc = nil
	file_maprotator_proto_goTypes = nil
	file_maprotator_proto_depIdxs = nil
}
