// compile with:
// protoc --go_out=. --go_opt=paths=source_relative --go-grpc_out=. --go-grpc_opt=paths=source_relative q2admin_rpc.proto

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.22.2
// source: q2admin_rpc.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Q2Admin_FetchStatus_FullMethodName = "/proto.Q2Admin/FetchStatus"
)

// Q2AdminClient is the client API for Q2Admin service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type Q2AdminClient interface {
	FetchStatus(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusResponse, error)
}

type q2AdminClient struct {
	cc grpc.ClientConnInterface
}

func NewQ2AdminClient(cc grpc.ClientConnInterface) Q2AdminClient {
	return &q2AdminClient{cc}
}

func (c *q2AdminClient) FetchStatus(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, Q2Admin_FetchStatus_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Q2AdminServer is the server API for Q2Admin service.
// All implementations must embed UnimplementedQ2AdminServer
// for forward compatibility
type Q2AdminServer interface {
	FetchStatus(context.Context, *StatusRequest) (*StatusResponse, error)
	mustEmbedUnimplementedQ2AdminServer()
}

// UnimplementedQ2AdminServer must be embedded to have forward compatible implementations.
type UnimplementedQ2AdminServer struct {
}

func (UnimplementedQ2AdminServer) FetchStatus(context.Context, *StatusRequest) (*StatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FetchStatus not implemented")
}
func (UnimplementedQ2AdminServer) mustEmbedUnimplementedQ2AdminServer() {}

// UnsafeQ2AdminServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to Q2AdminServer will
// result in compilation errors.
type UnsafeQ2AdminServer interface {
	mustEmbedUnimplementedQ2AdminServer()
}

func RegisterQ2AdminServer(s grpc.ServiceRegistrar, srv Q2AdminServer) {
	s.RegisterService(&Q2Admin_ServiceDesc, srv)
}

func _Q2Admin_FetchStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Q2AdminServer).FetchStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Q2Admin_FetchStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Q2AdminServer).FetchStatus(ctx, req.(*StatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Q2Admin_ServiceDesc is the grpc.ServiceDesc for Q2Admin service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Q2Admin_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Q2Admin",
	HandlerType: (*Q2AdminServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FetchStatus",
			Handler:    _Q2Admin_FetchStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "q2admin_rpc.proto",
}
