// compile with:
// protoc --go_out=. --go_opt=paths=source_relative teleport.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v4.22.2
// source: teleport.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// An individual destination for teleporting
type TeleportDestination struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name    string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`       // alias "pf-tdm-de3"
	Address string `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"` // ip:port
	Map     string `protobuf:"bytes,3,opt,name=map,proto3" json:"map,omitempty"`         // currently loaded map
	Players string `protobuf:"bytes,4,opt,name=players,proto3" json:"players,omitempty"` // comma delimited string of player names
}

func (x *TeleportDestination) Reset() {
	*x = TeleportDestination{}
	if protoimpl.UnsafeEnabled {
		mi := &file_teleport_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TeleportDestination) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TeleportDestination) ProtoMessage() {}

func (x *TeleportDestination) ProtoReflect() protoreflect.Message {
	mi := &file_teleport_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TeleportDestination.ProtoReflect.Descriptor instead.
func (*TeleportDestination) Descriptor() ([]byte, []int) {
	return file_teleport_proto_rawDescGZIP(), []int{0}
}

func (x *TeleportDestination) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TeleportDestination) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *TeleportDestination) GetMap() string {
	if x != nil {
		return x.Map
	}
	return ""
}

func (x *TeleportDestination) GetPlayers() string {
	if x != nil {
		return x.Players
	}
	return ""
}

// All info needed to respond to a teleport command
type TeleportReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ReplyDate     int64                  `protobuf:"varint,1,opt,name=reply_date,json=replyDate,proto3" json:"reply_date,omitempty"` // unix timestamp
	ActiveServers []*TeleportDestination `protobuf:"bytes,2,rep,name=active_servers,json=activeServers,proto3" json:"active_servers,omitempty"`
	EmptyServers  string                 `protobuf:"bytes,3,opt,name=empty_servers,json=emptyServers,proto3" json:"empty_servers,omitempty"` // comma delimited list of names
}

func (x *TeleportReply) Reset() {
	*x = TeleportReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_teleport_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TeleportReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TeleportReply) ProtoMessage() {}

func (x *TeleportReply) ProtoReflect() protoreflect.Message {
	mi := &file_teleport_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TeleportReply.ProtoReflect.Descriptor instead.
func (*TeleportReply) Descriptor() ([]byte, []int) {
	return file_teleport_proto_rawDescGZIP(), []int{1}
}

func (x *TeleportReply) GetReplyDate() int64 {
	if x != nil {
		return x.ReplyDate
	}
	return 0
}

func (x *TeleportReply) GetActiveServers() []*TeleportDestination {
	if x != nil {
		return x.ActiveServers
	}
	return nil
}

func (x *TeleportReply) GetEmptyServers() string {
	if x != nil {
		return x.EmptyServers
	}
	return ""
}

var File_teleport_proto protoreflect.FileDescriptor

var file_teleport_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x74, 0x65, 0x6c, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x6f, 0x0a, 0x13, 0x54, 0x65, 0x6c, 0x65, 0x70,
	0x6f, 0x72, 0x74, 0x44, 0x65, 0x73, 0x74, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x12,
	0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x10, 0x0a, 0x03,
	0x6d, 0x61, 0x70, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x61, 0x70, 0x12, 0x18,
	0x0a, 0x07, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x73, 0x22, 0x96, 0x01, 0x0a, 0x0d, 0x54, 0x65, 0x6c,
	0x65, 0x70, 0x6f, 0x72, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x1d, 0x0a, 0x0a, 0x72, 0x65,
	0x70, 0x6c, 0x79, 0x5f, 0x64, 0x61, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09,
	0x72, 0x65, 0x70, 0x6c, 0x79, 0x44, 0x61, 0x74, 0x65, 0x12, 0x41, 0x0a, 0x0e, 0x61, 0x63, 0x74,
	0x69, 0x76, 0x65, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x1a, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x54, 0x65, 0x6c, 0x65, 0x70, 0x6f,
	0x72, 0x74, 0x44, 0x65, 0x73, 0x74, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0d, 0x61,
	0x63, 0x74, 0x69, 0x76, 0x65, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x73, 0x12, 0x23, 0x0a, 0x0d,
	0x65, 0x6d, 0x70, 0x74, 0x79, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x73, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0c, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x73, 0x42, 0x29, 0x5a, 0x27, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x70, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x66, 0x6c, 0x69, 0x6e, 0x67, 0x65, 0x72, 0x2f, 0x71, 0x32,
	0x61, 0x64, 0x6d, 0x69, 0x6e, 0x64, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_teleport_proto_rawDescOnce sync.Once
	file_teleport_proto_rawDescData = file_teleport_proto_rawDesc
)

func file_teleport_proto_rawDescGZIP() []byte {
	file_teleport_proto_rawDescOnce.Do(func() {
		file_teleport_proto_rawDescData = protoimpl.X.CompressGZIP(file_teleport_proto_rawDescData)
	})
	return file_teleport_proto_rawDescData
}

var file_teleport_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_teleport_proto_goTypes = []interface{}{
	(*TeleportDestination)(nil), // 0: proto.TeleportDestination
	(*TeleportReply)(nil),       // 1: proto.TeleportReply
}
var file_teleport_proto_depIdxs = []int32{
	0, // 0: proto.TeleportReply.active_servers:type_name -> proto.TeleportDestination
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_teleport_proto_init() }
func file_teleport_proto_init() {
	if File_teleport_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_teleport_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TeleportDestination); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_teleport_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TeleportReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_teleport_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_teleport_proto_goTypes,
		DependencyIndexes: file_teleport_proto_depIdxs,
		MessageInfos:      file_teleport_proto_msgTypes,
	}.Build()
	File_teleport_proto = out.File
	file_teleport_proto_rawDesc = nil
	file_teleport_proto_goTypes = nil
	file_teleport_proto_depIdxs = nil
}
